version: "2"

exclude_patterns:
- "public/"
- "po/"
- "sql/"
- "po/"
- ".github/"
- "po/"
- "*.sh"
- "*.twig"
- "*.xml"
- "**/vendor/"
- "**/node_modules/"

plugins:
  git-legal:
    enabled: true
  markdownlint:
    enabled: true

