version: "2"

exclude_patterns:
- "public/"
- "po/"
- "sql/"
- "po/"
- ".github/"
- "po/"
- ".mdlrc"
- ".gitignore"
- ".gitmodules"
- ".env-example"
- "**/*.sh"
- "**/*.yml"
- "**/*.json"
- "**/*.rb"
- "**/*.twig"
- "**/*.xml"
- "**/vendor/"
- "**/node_modules/"

plugins:
  git-legal:
    enabled: true
  markdownlint:
    enabled: true

