exclude_patterns:
- "public/"
- "po/"
- "**/vendor/"
- "**/node_modules/"

plugins:
  git-legal:
    enabled: true
  markdownlint:
    enabled: true
  phpcodesniffer:
    enabled: true

engines:
  phpcodesniffer:
    enabled: true
    config:
      file_extensions: "php"
      standard: "tests/phpcs.xml"
      ignore_warnings: true
      encoding: utf-8

ratings:
  paths:
  - "**.php"
