dist: trusty

language: php

services:
  - mysql

php:
  - "7.0"
  - "7.1"
  - "7.2"

sudo: required

env:
  matrix:
    - CI_TYPE=phpunit

before_script:
  - ./scripts/ci/install.sh

script:
  - ./scripts/po_to_mo.php
  - ./scripts/ci/ci-$CI_TYPE.sh

install:
    # flags to pass to install
    - flags="--ansi --prefer-dist --no-interaction --optimize-autoloader --no-suggest --no-progress"
    # install dependencies using system provided composer binary
    - composer install $flags

after_success:
  - bash <(curl -s https://codecov.io/bash)

matrix:
  fast_finish: true
  include:
    - os: osx
      language: generic
      php: "7.2"
      env: CI_TYPE=phpunit
      before_install:
        - brew update
        - brew install php72 mariadb
        - brew install php72-xdebug
        - sed -i -e 's/^memory_limit = .*/memory_limit = -1/' /usr/local/etc/php/7.2/php.ini
        - curl https://getcomposer.org/installer | php
        - ln -s "`pwd`/composer.phar" /usr/local/bin/composer

cache:
  apt: true
  directories:
    - $HOME/.composer/cache/
    - $HOME/.cache/bower
    - $HOME/.npm
    - /var/cache/apt

addons:
  apt:
    update: true
    packages:
    - git
    - mysql-server
    - nginx
    sources:
      - mysql-5.7-trusty