dist: trusty

language: php

services:
  - mysql

php:
  - "7.1"
  - "7.2"

sudo: required

env:
  matrix:
    - CI_TYPE=phpunit

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - if [[ "$TRAVIS_OS_NAME" != "osx" ]]; then ./cc-test-reporter before-build; fi
  - ./scripts/ci/install.sh

script:
  - ./scripts/po_to_mo.php
  - ./scripts/ci/ci-$CI_TYPE.sh

install:
    # flags to pass to install
    - flags="--ansi --prefer-dist --no-interaction --optimize-autoloader --no-suggest --no-progress"
    # install dependencies using system provided composer binary
    - composer install $flags

after_success:
  - bash <(curl -s https://codecov.io/bash)

after_script:
  - if [[ "$TRAVIS_OS_NAME" != "osx" ]]; then ./scripts/ci/codeclimate.sh; fi

matrix:
  fast_finish: true
  include:
    - php: "7.2"
      env: CI_TYPE=phpcs

    - os: osx
      language: generic
      php: "7.2"
      env: CI_TYPE=phpunit
      before_install:
        - ./scripts/ci/install-osx.sh

cache:
  apt: true
  directories:
    - $HOME/.composer/cache/
    - $HOME/.cache/bower
    - $HOME/.npm
    - /var/cache/apt
    - ~/Library/Caches/Homebrew

addons:
  apt:
    update: true
    packages:
    - git
    - mysql-server
    - nginx
    sources:
      - mysql-5.7-trusty